### ISSUE TITLE
Disk config not properly configured

### ISSUE THREAD

**Issue by maasencioh** [zakodium/adonis-datadrive#18]
I've migrated recently to the newest version, and I realize that my previous code isn't working, having the following error:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:363:5)
    at validateString (node:internal/validators:119:11)
    at join (node:path:429:7)
    at LocalDriver.makePath (C:\Users\maase\Documents\GitHub\mylims\mylims\node_modules\@adonisjs\drive\build\src\Drivers\Local.js:66:78)
    at LocalDriver.putStream (C:\Users\maase\Documents\GitHub\mylims\mylims\node_modules\@adonisjs\drive\build\src\Drivers\Local.js:165:35)
    at DataDrive.putStream (C:\Users\maase\Documents\GitHub\mylims\mylims\node_modules\adonis-datadrive\src\DataDrive.ts:108:21)
    at Import.importFile (C:\Users\maase\Documents\GitHub\mylims\mylims\addons\file-sync\Commands\Import.ts:218:35)
    at Import.handleFileSyncOption (C:\Users\maase\Documents\GitHub\mylims\mylims\addons\file-sync\Commands\Import.ts:160:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Import.executeImporter (C:\Users\maase\Documents\GitHub\mylims\mylims\addons\file-sync\Commands\Import.ts:118:7) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

Investigating I've seen that the configuration that `@ioc:Adonis/Core/Drive` received was 
```ts
{
  driver: 'local',
  config: { root: getConfig('fileSync').root },
}
```

Instead of
```ts
{
   root: getConfig('fileSync').root,
}
```

As is specified in [here](https://github.com/adonisjs/drive/blob/cde09e84ad5214b27f9c4e9e075038eea66036cd/src/Drivers/Local.ts#L65).

I don't know if I have a misconfiguration or if this is a bug in this library

**Comment by targos** [comment]
This library only passes the drive's name to `@ioc:Adonis/Core/Drive`. There must be an issue in your config.

Here's an example from one of my projects:

```ts
// config/drive.ts
import { DriveConfig } from '@ioc:Adonis/Core/Drive';
import Env from '@ioc:Adonis/Core/Env';

const driveConfig: DriveConfig = {
  disk: 'local',

  disks: {
    local: {
      driver: 'local',
      visibility: 'private',
      root: Env.get('DRIVE_DATA_ROOT'),
    },
    tmp: {
      driver: 'local',
      visibility: 'private',
      root: Env.get('DRIVE_TMP_ROOT'),
    },
  },
};

export default driveConfig;
```

```ts
// config/datadrive.ts
import { DataDriveConfig } from '@ioc:Zakodium/DataDrive';

const dataDriveConfig: DataDriveConfig = {
  drives: {
    sampleMetadata: {
      disk: 'local',
      prefix: 'upload/metadata',
    },
    tmpUploads: {
      disk: 'tmp',
      prefix: 'tmp/upload',
    },
  },
};

export default dataDriveConfig;
```

**Comment by maasencioh** [comment]
How is your contract? If I modify it like that it doesn't recognize the driver in `LocalFileSystemStorageConfig`

```ts
// contracts/drive.ts
declare module '@ioc:Adonis/Core/Drive' {
  import { LocalFileSystemStorageConfig } from '@slynova/flydrive';

  interface DisksList {
    local: {
      config: LocalFileSystemStorageConfig;
    };
  }
}
```

**Comment by targos** [comment]
```ts
declare module '@ioc:Adonis/Core/Drive' {
  interface DisksList {
    local: {
      config: LocalDriverConfig;
    };
    tmp: {
      config: LocalDriverConfig;
    };
  }
}
```

**Comment by maasencioh** [comment]
Thank you, this solved my problem
